name: financial_wizard
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - streamlit>=1.30.0
      - langchain>=0.1.0
      - langchain-pinecone>=0.1.0
      - langchain-cohere>=0.1.0
      - pandas>=2.0.0
      - python-dotenv
      - pinecone-client
      - cohere
      - transformers
      - accelerate
